---
site_name: Certificate of Participation
site_url: https://pioneershub.github.io/participation_certificate/
site_author: Alexander Hendorf
site_description: >-
  Certificate of Participation: Create thousands of signed, secure PDFs that easy to validate.
# Repository
repo_name: PioneersHub/participation_certificate
repo_url: https://github.com/PioneersHub/participation_certificate

#
nav:
  - Design & Ship PDFs at Ease: index.md
  - installation.md
  - walkthrough.md
  - Best Practices: bestpractice.md
  - License: license.md
  - Pioneers Hub website: https://pioneershub.org/


theme:
  name: material
  icon:
    logo: fontawesome/solid/certificate
  language: en
  palette:
    primary: custom
  features:
    - navigation.instant
  site_url: https://pioneershub.github.io/participation_certificate/


markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

plugins:
  - social:
      cards_layout_options:
        background_color: "#ffffff"
        color: "#000000"
  - search
  - tags
  - glightbox
  - open-in-new-tab

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
    version:
      provider: mike
      default: stable

hooks:
  - scripts/hook_copyright_year.py

# Copyright
copyright: >
  Copyright &copy; 2024 Pioneers Hub gGmbH –
  <a href="#__consent">Change cookie settings</a>
