[project]
name = "Certificates of Participation"
version = "0.1.0"
description = "Generate participation certificates for events."
authors = ["Alexander CS Hendorf <hendorf@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

# Dependencies
[dependencies]
python = ">=3.12.3,<3.13"
pixi-pycharm = ">=0.0.5,<0.1"
pydantic = ">=2.7.3,<2.8"

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."


[feature.py312.dependencies]
python = "3.12.*"

[host-dependencies]
python = "*"
pip = "*"

[feature.test.dependencies]
pytest = "*"
pytest-md = "*"
pytest-emoji = "*"
hypothesis = "*"
pytest-cov = "*"
[feature.test.tasks]
test = "pytest"

[tool.pixi.dependencies]
ruff = ">=0.4.8,<0.5"

[feature.lint.dependencies]
pre-commit = "*"
[feature.lint.tasks]
lint = "pre-commit run --all"

[environments]
default = ["test"]
lint = ["lint"]
py312 = ["py312", "test"]
