[project]
name = "Certificates for Participation"
version = "0.1.0"
description = "Generate participation certificates for events."
authors = ["Alexander CS Hendorf <hendorf@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

# Dependencies
[dependencies]
python = ">=3.12.3,<3.13"
pixi-pycharm = ">=0.0.5,<0.1"


[feature.py312.dependencies]
python = "3.12.*"

[tool.pixi.dependencies]
ruff = ">=0.4.8,<0.5"

# Environments
[tool.pixi.environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }


# Test
[feature.test.pypi-dependencies]
pytest = "*"

[feature.test.tasks]
test = "pytest"

[feature.lint.dependencies]
pre-commit = "*"
[feature.lint.tasks]
lint = "pre-commit run --all"

[environments]
default = ["test"]
lint = ["lint"]
py312 = ["py312", "test"]